### ISSUE TITLE
Y-Axis seems to be inverted on arcan_sdl (SDL2)

### ISSUE THREAD

**Issue by ChrisOboe** [letoram/durden#61]
Hi,

i just build arcan to test it. When i run durden in arcan_sdl the y-axis seems to be inverted.
Here is a screenshot: https://imgur.com/a/RUBGNwN

This doesn't happen when i run welcome or console applications in arcan. I currently haven't tested other video platforms yet. 

I'm using arcan 0.6.0.1 and durden 0.6.1.

**Comment by letoram** [comment]
It's due to how durden handles multi-screen code that turned out to be .. problematic. A temporary workaround should be to try and switch to simple-mode (global/config/system/display_mode=simple):

or from the command-line: arcan_db add_appl_kv durden display_simple true

**Comment by letoram** [comment]
(might need to disable the workaround mentioned above) - 
fixed in arcan 8a14e0e0.
