### ISSUE TITLE
Weird mkdir errors when running durden with command line options

### ISSUE THREAD

**Issue by demostanis** [letoram/durden#63]
When running `durden --help`, weird errors are being printed to standard error:
```
mkdir: unrecognized option '--help/durden/output'
Try 'mkdir --help' for more information
mkdir: unrecognized option '--help/durden/ipc'
Try 'mkdir --help' for more information.
[...]
```
It's because [`dist/durden`](https://github.com/letoram/durden/blob/78af4b8719c72dc58522302c3639fba6245e6b8b/distr/durden#L4) doesn't expect them, despite that durden itself does.
Running latest version on a Void Linux VM.

**Comment by letoram** [comment]
not that weird - the launcher script was written/intended for a "startx" like situation where you needed something to bring the desktop up without thinking about it or even having a CLI so not intended for interactive use. For any refined arguments and control, using arcan to specify things is the way to go. Might reconsider if / when we add more support scripts to do things like import / translate dotfiles from i3 and so on.
